### ISSUE TITLE
No such directory bin/test

### ISSUE THREAD

**Issue by zackshapiro** [rlister/slackbotsy_example#1]
Hey Ric,

Thanks for writing this. Using it as the basis to set up my own Slackbot. I'm going through your tutorial and running `OUTGOING_TOKEN=123 bin/test botsy ping` and in return, I get `no such file or directory: bin/test`.

I created `~/bin/test` and then ran `sudo OUTGOING_TOKEN=123 bin/test botsy ping` but then get `sudo: bin/test: command not found`

Any idea on how to get this working correctly?

**Comment by rlister** [comment]
@zackshapiro the `bin/test` file is a file in the `slackbotsy_example` repo. I have added an explicit `cd slackbotsy_example` to the README after the clone command, to make this clearer.

So in summary, you should be able to do:

```
$ git clone https://github.com/rlister/slackbotsy_example.git
$ cd slackbotsy_example
$ ls bin
```

and see the `test` file.

If you don't see the file there, or can't run it for some reason, please let me know details of your platform so I can check.

**Comment by zackshapiro** [comment]
Thanks Ric

Best,
Zack
